apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: roar-db
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: roar-db
  template:
    metadata:
      labels:
        app: roar-db
        name: mysql
    spec:
      containers:
      - name: mysql
        image: quay.io/techupskills/roar-db:v2
        env:
        - name: MYSQL_DATABASE
          value: registry
        - name: MYSQL_PASSWORD
          value: admin
        - name: MYSQL_ROOT_PASSWORD
          value: root+1
        - name: MYSQL_USER
          value: admin
        imagePullPolicy: Always
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
